# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-19 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infiniti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='foto',
            field=models.ImageField(default='imagens/2.png', upload_to=''),
        ),
    ]
