# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-19 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infiniti', '0003_auto_20170319_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='imagens'),
        ),
    ]
