# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-19 22:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infiniti', '0004_auto_20170319_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='foto',
        ),
    ]
